# Generated by Django 4.0.6 on 2022-07-26 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0002_rename_pedido_id_lineapedido_pedido_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineapedido',
            options={'ordering': ['id'], 'verbose_name': 'Linea pedido', 'verbose_name_plural': 'Lineas pedidos'},
        ),
    ]
