# Generated by Django 4.0.2 on 2022-03-07 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0002_auto_20200622_1622'),
        ('Servicios', '0002_auto_20210310_1222'),
    ]

    operations = [
    ]
